In [55]:
import pandas as pd
df=pd.read_csv("/Users/harshit_mac/Desktop/datascience/titanic.csv")
df=df[['Survived','Pclass','Sex','Age','Fare']]

In [56]:
df

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [57]:
target=df.Survived

In [58]:
inputs=df.drop(['Survived'],axis='columns')

In [59]:
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [60]:
dum=pd.get_dummies(inputs.Sex)

In [61]:
dum

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [62]:
inputs=pd.concat([inputs,dum],axis='columns')

In [63]:
inputs.drop(['Sex'],axis='columns',inplace=True)

In [64]:
inputs

Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [65]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [66]:
import math as mt

In [68]:
k=inputs.Age.mean()

In [69]:
k

29.69911764705882

In [70]:
k=mt.ceil(k)

In [71]:
k

30

In [72]:
inputs.Age=inputs.Age.fillna(k)

In [89]:
inputs

Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3  30.0  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [90]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)

In [76]:
len(X_test)

179

In [77]:
len(inputs)

891

In [91]:
from sklearn.naive_bayes import GaussianNB
model1=GaussianNB()

In [92]:
model1.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [93]:
model1.score(X_test,y_test)

0.8156424581005587

In [94]:
y_test[:10]

706    1
52     1
551    0
799    0
117    0
133    1
559    1
388    0
610    0
718    0
Name: Survived, dtype: int64

In [95]:
model1.predict(X_test[:10])

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [96]:
model1.predict_proba(X_test[:10])

array([[0.04019878, 0.95980122],
       [0.00256629, 0.99743371],
       [0.97434774, 0.02565226],
       [0.07648622, 0.92351378],
       [0.97579023, 0.02420977],
       [0.03551683, 0.96448317],
       [0.08257888, 0.91742112],
       [0.98879949, 0.01120051],
       [0.0766073 , 0.9233927 ],
       [0.98906497, 0.01093503]])

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
inputs.Sex=le.fit_transform(inputs.Sex)

In [21]:
inputs

Pclass  Sex   Age     Fare
0         3    1  22.0   7.2500
1         1    0  38.0  71.2833
2         3    0  26.0   7.9250
3         1    0  35.0  53.1000
4         3    1  35.0   8.0500
..      ...  ...   ...      ...
886       2    1  27.0  13.0000
887       1    0  19.0  30.0000
888       3    0   NaN  23.4500
889       1    1  26.0  30.0000
890       3    1  32.0   7.7500

[891 rows x 4 columns]

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('Sex',OneHotEncoder(),[1])],remainder='passthrough')

In [30]:
inputs=ct.fit_transform(inputs)
inputs

array([[ 0.    ,  1.    ,  0.    , ...,  3.    , 22.    ,  7.25  ],
       [ 1.    ,  0.    ,  1.    , ...,  1.    , 38.    , 71.2833],
       [ 1.    ,  0.    ,  1.    , ...,  3.    , 26.    ,  7.925 ],
       ...,
       [ 1.    ,  0.    ,  1.    , ...,  3.    ,     nan, 23.45  ],
       [ 0.    ,  1.    ,  0.    , ...,  1.    , 26.    , 30.    ],
       [ 0.    ,  1.    ,  0.    , ...,  3.    , 32.    ,  7.75  ]])

In [97]:
import numpy as np
k=np.isnan(inputs)

In [36]:
k

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])